HealthWarehouse/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from django.urls.conf import include
from django.conf.urls.static import static
from HealthWarehouse import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.default.urls')),     
    path('app/',include("app.urls")),
    path('',RedirectView.as_view(url='app/'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.urls.conf import include
from app import views
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework import routers



router = routers.DefaultRouter() 
router.register(r'medicine', views.MedicineViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'review', views.ReviewViewSet)


urlpatterns = [
    # static page urls here
    path('index/',views.IndexView.as_view()),
    path('about/',views.AboutView.as_view()),
    
    path('contact/',views.ContactView.as_view()),
    path('contact/send',views.contactform),
    
    #dynamic pages urls here
    path('store/',views.StoreView.as_view(),name='store'),
    path('store/medicine/view/<int:id>',views.MedicineDetailView.as_view(),name='med_detail'),
    path('store/medicine/cart/<int:id>',views.MedicineCartView.as_view(),name='med_cart'),
    path('store/medicine/order/',views.OrderMedicine,name='med_order'),
    
    path('orders/',views.OrdersView.as_view(),name='orders'),
    path('orders/review/<int:id>',views.OrdersReviewView.as_view(),name='order_review'),
    path('orders/review/done',views.ReviewDone,name='order_rating_done'),
     
    path('profile/edit/<int:pk>',views.ProfileUpdateView.as_view()),
     
    path(r'api/', include(router.urls)),
    path(r'api-token-auth/', obtain_jwt_token),
    
    path('',RedirectView.as_view(url='index/'))
]

app/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator,\
    RegexValidator

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(to=User,on_delete=CASCADE)
    bio = models.TextField(null=True)
    disease = models.TextField(null=True)
    age = models.IntegerField(validators = [MinValueValidator(18),MaxValueValidator(100)],null=True)
    full_address = models.TextField(null=True)
    contact_no = models.CharField(max_length=20,validators=[RegexValidator("^0?[5-9]{1}\d{9}$")],null=True)
    def __str__(self):
        return self.user
    
class Medicine(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True,blank=True) 
    medicine_img = models.ImageField(upload_to="medicine//")
    price = models.FloatField(default=0.0,validators=[MinValueValidator(0.0)])
    mfg_date = models.DateField(null=True,blank=True)
    exp_date = models.DateField(null=True,blank=True) 
    cr_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name
    
class Orders(models.Model):
    user = models.ForeignKey(to=User,on_delete=CASCADE,null=True)
    medicine = models.ForeignKey(to=Medicine,on_delete=CASCADE)
    quantity = models.IntegerField(default=1,validators=[MinValueValidator(0)])
    total_price = models.FloatField(null=True)
    delivery_status = models.CharField(max_length=50,default='ordered',choices=(('ordered','Ordered'),('ordered','Ordered'),('shipping','Shipping'),('delivered','Delivered'),))    
    cr_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "%s(%s)" % (self.medicine,self.user)
    
         
class Review(models.Model):
    orders = models.ForeignKey(to=Orders,on_delete=CASCADE,null=True)
    rating = models.IntegerField(default=1,choices=((1,"One Rating"),(2,"Two Rating"),(3,"Three Rating"),(4,"Four Rating"),(5,"Five Rating"),))
    comment = models.TextField(null=True,blank=True)
    def __str__(self):
        return "%s(%s)" % (self.orders,self.rating)
    

app/templates/app/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>About Us</h1>
<hr>
<h3>Our Key Values: </h3>
<div class="row">
<div class="col-sm-6">
<ul class="list-group">
  <li class="list-group-item">The courage to dream</li>
  <li class="list-group-item">The thirst for knowledge</li>
  <li class="list-group-item">The passion to excel</li>
  <li class="list-group-item">The conviction to break free</li>
  <li class="list-group-item">The vision to build</li>
  <li class="list-group-item">The skill to achieveli>
  <li class="list-group-item">The character to inspire</li>
  <li class="list-group-item">The location which is prime</li>
  <li class="list-group-item">The dedicated teachers</li>
</ul>
</div>
<div class="col-md-6">
	<div class="embed-responsive embed-responsive-16by9">
		<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/NC4TiWOqLx0" title="Introductory Video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	  </div>

</div>

</div>
{% endblock %}

app/templates/app/cart.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-uppercase text-center"> Cart Page </h1>
<hr>
<div class="row">
    <div class="col-md-6">
        <div class="pt-3 pl-5 pr-5 pb-1">
         <h6 class="text-uppercase text-center">Medicine's Preview:</h6><br>
         <img class="img-thumbnail" width="100%" src="/media/{{ med.medicine_img }}" alt="Medicine image not found">
        </div>
     </div>

  <div class="col-md-6">
    <div class=" mt-5 text-justify">
         <h5 >Name :  {{ med.name }} </h5> 
         <p >About :  {{ med.description }} </p> 
         <p >Price :  {{ med.price }} </p>
         <h6 >Manufactured Date :  {{ med.mfg_date }} </h6>
         <h6 >Expiry Date :  {{ med.exp_date }} </h6>
         <p >Published Date :  {{ med.cr_date }} </p>
         <form action="{% url 'med_order' %}" method="POST">
          {% csrf_token %}
             <input type="hidden" name="m_id" value="{{ med.id }}" > 
             <label for="qty">Quantity : </label>
             <input required class="form-control mb-3" type="number" name="qty" max="50" min="1" value=1 step="1">
             <input type="submit" class="btn btn-secondary btn-block" value="Order">
         <a href="{% url 'store' %}" class="btn btn-outline-secondary btn-block">Back</a>
         </form>
          
    </div>
</div>   

<!-- name, description, medicine_img, price 
mfg_date , exp_date ,cr_date
-->
</div>
{% endblock %}

app/templates/app/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Contact Us</h1>
<hr>
<div class="row">
<div class="col-sm-6">
<div class="embed-responsive embed-responsive-16by9">
<iframe class="embed-responsive-item" 
src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3718.6783107360206!2d81.64076161424912!3d21.24460128575218!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a28ddfc56a97537%3A0x763fe09728aad001!2sGhadi%20Chowk%20Raipur!5e0!3m2!1sen!2sin!4v1630305835160!5m2!1sen!2sin"
 frameborder="0" style="border:0" allowfullscreen></iframe>

</div>
</div>
<div class="col-sm-6">
    <form action="/app/contact/send" method="post">
    {% csrf_token %}
        <div class="form-group">
            <label >Name : </label>
            <input required type="text" class="form-control" name="name" placeholder="Ex. Alpha Beta">
          </div>
          <div class="form-group">
            <label >Email address :</label>
            <input required type="email" class="form-control" name="email" placeholder="name@example.com">
          </div>
          <div class="form-group">
            <label >Contact No</label>
            <input required type="tel" class="form-control" name="phoneno" placeholder="+91 98765*****">
          </div>
        
            <div class="form-group">
              <label >Enquiry/Feedback/Message :</label>
              <textarea required class="form-control" name="msg" rows="3"></textarea>
            </div>

            <input class="btn btn-outline-primary btn-block" type="submit" value="Done">
         
    </form>
</div>
    
</div>
{% endblock %}

app/templates/app/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% if request.GET.msg == 0 %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>NOTIFICATION!</strong> Something went wrong try again later.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% elif request.GET.msg == 1 %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>NOTIFICATION!</strong> Enquiry form submitted successfully.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
    
<div class="h3 text-uppercase "> Overview </div>
<hr>
<div class="row">

    <div class="col-md-6">
        <div class="h4"> Objective</div>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut a dui sed ipsum suscipit tincidunt. Nulla odio sem, mollis non maximus ut, hendrerit id urna. Quisque id velit ac lorem facilisis scelerisque sed eu sem. Integer vulputate massa sed tempor pretium. Fusce sit amet maximus ipsum. Nulla eu mauris in neque aliquam molestie. Quisque tristique lacus velit, quis blandit erat dapibus eget. Vivamus sem urna, sodales a tempor eu, rhoncus et ligula.
        </p>
        <p>
            Duis ac consectetur turpis. Sed odio justo, mollis nec condimentum a, convallis non ante. Donec quis condimentum erat, non tempus arcu. Vestibulum pulvinar, mi quis cursus elementum, sapien turpis viverra nisl, ac iaculis nulla quam accumsan magna. Sed vel nibh tellus. Suspendisse eu felis sed elit pharetra efficitur. Integer faucibus nisi id nisl condimentum tincidunt. Sed quam odio, tempus nec cursus eu, vestibulum et urna. Aenean quam dolor, feugiat vitae viverra ac, condimentum eget ante. Aenean est risus, lacinia a ipsum sit amet, tempor porttitor lorem. Donec justo lorem, blandit at nulla et, sodales consectetur velit. Nam tincidunt augue orci, in sollicitudin arcu dapibus ac.
        </p>

    </div>
    <div class="col-sm-6">
        <div class="carousel slide" data-ride="carousel" id="car1">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="img-fluid" src="{% static 'images/c1.jpg' %}" />
                </div>
                <div class="carousel-item">
                    <img class="img-fluid" src="{% static 'images/c2.jpg' %}" />
                </div>
                <div class="carousel-item">
                    <img class="img-fluid" src="{% static 'images/c3.jpg' %}" />
                </div>
                <div class="carousel-item">
                    <img class="img-fluid" src="{% static 'images/c4.jpg' %}" />
                </div>
            </div>
            <a href="#car1" data-slide="prev" class="carousel-control-prev"> <span
                class="carousel-control-prev-icon"></span>
            </a> 
            <a href="#car1" data-slide="next" class="carousel-control-next"> <span
                class="carousel-control-next-icon"></span>
            </a>
        
        </div>
        
        
        </div>
</div>
<hr>
<div class="row m-2">
    <p>
        Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ut pulvinar metus, a sollicitudin libero. Nullam libero massa, sodales ut laoreet sed, posuere sed velit. Nulla tempor, urna vel vestibulum tincidunt, purus ipsum rhoncus ante, ut bibendum lacus turpis et nisi. In consectetur libero non felis aliquam, eget ultricies diam finibus. Morbi interdum varius ultrices. Praesent auctor magna in sodales ullamcorper. Nam a molestie lacus, non tempor magna. Donec eu justo eu massa venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas non tellus tortor. Praesent fringilla sem eu cursus fermentum.
    </p>
    <p>
        Cras consectetur nisi non purus sagittis dignissim sit amet placerat metus. Donec ut varius elit, at cursus felis. Mauris placerat tempor diam quis vehicula. Donec aliquam sem urna, a euismod ipsum tristique quis. Ut cursus augue id massa tristique, id sollicitudin felis consequat. Vestibulum blandit molestie massa eget faucibus. In varius magna a vehicula aliquet. Quisque tristique mi et quam sodales eleifend. Fusce volutpat eros sit amet elementum convallis. Cras dapibus massa eget lorem laoreet sodales. Morbi a porta quam, ut accumsan dolor. Aliquam convallis ac dolor in tincidunt. Nullam massa sapien, dapibus sed feugiat quis, consequat quis dolor. Suspendisse hendrerit dui nec commodo aliquam. Etiam at justo vitae magna dapibus pulvinar in vel nisi.
    </p>
</div>
<hr>
{% endblock %}

app/templates/app/med_detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-uppercase text-center"> {{ medicine.name }}'s Detail Page </h1>
<hr>
<div class="row">
  <div class="col-md-6">
    <div class="text-justify">
         <h5 >Name :  {{ medicine.name }} </h5> 
         <p >About :  {{ medicine.description }} </p> 
         <p >Price :  {{ medicine.price }} </p>
         <h6 >Manufactured Date :  {{ medicine.mfg_date }} </h6>
         <h6 >Expiry Date :  {{ medicine.exp_date }} </h6>
         <p >Published Date :  {{ medicine.cr_date }} </p>
          
         <a href="{% url 'store' %}" class="btn btn-outline-secondary btn-block">Back</a>
         <a href="/app/store/medicine/cart/{{ medicine.id }}" class="btn btn-secondary btn-block">Buy</a>  
           
    </div>
    <hr>
    <div>
      <h3>{{ medicine.name }}'s Review </h3>
      {% if reviews|length == 0 %}
      <p>No reviews found</p>
      {% else %}
      {% for review in reviews %}
      <i>
        "{{ review.comment }}",Rated - {{ review.rating }} <br>
        ~ <strong>{{ review.orders.user }}</strong>
        </i>
         <br>
      {% endfor %}
      {% endif %}
    
    </div>
</div>   
 <div class="col-md-6">
   <div class="pt-3 pl-5 pr-5 pb-1">
    <h6 class="text-uppercase text-center">Medicine's Preview:</h6><br>
    <img class="img-thumbnail" width="100%" src="/media/{{ medicine.medicine_img }}" alt="Medicine image not found">
   </div>
</div>
<!-- name, description, medicine_img, price 
mfg_date , exp_date ,cr_date
-->
</div>
{% endblock %}

app/templates/app/order_review.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-uppercase text-center"> Order Rating Section </h1>
<hr>
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                <div class="text-center">
                    <h5 >Name :  {{ o.medicine.name }} </h5> 
                    <p >Price :  {{ o.medicine.price }} </p>
                    <h6 >Expiry Date :  {{ o.medicine.exp_date }} </h6> 
                   </div> 
        
            </div>
            <div class="col-md-6">
                <h6 class="text-uppercase text-center">Medicine's Preview:</h6><br>
                <img class="img-thumbnail" width="100%" src="/media/{{ o.medicine.medicine_img }}" alt="Medicine image not found">
            
            </div>
        </div>
     </div>

  <div class="col-md-6">
    <div class=" mt-5 text-justify">
    	
         <h5 >Order Date :  {{ o.cr_date }} </h5> 
         <h5 >Quantity :  {{ o.quantity }} </h5> 
         <h5 >Status :  {{ o.delivery_status }} </h5>
         <hr>
         <form action="{% url 'order_rating_done' %}" method="POST">
            {% csrf_token %}
             <input type="hidden" name="o_id" value="{{ o.id }}" > 
             
             <div class="form-group">
                <label >Select Rating</label>
                <select class="form-control" name="rating">
                  <option value="1">One Rating</option>
                  <option value="2">Two Rating</option>
                  <option value="3">Three Rating</option>
                  <option value="4">Four Rating</option>
                  <option value="5">Five Rating</option>
                </select>
              </div>
              
              <div class="form-group">
                <label >Review / Comment</label>
                <textarea class="form-control" name="comment" rows="3"></textarea>
              </div>
             
             <input type="submit" class="btn btn-secondary btn-block" value="Done">
         <a href="{% url 'orders' %}" class="btn btn-outline-secondary btn-block">Back</a>
         </form>
          
    </div>
</div>   

<!-- name, description, medicine_img, price 
mfg_date , exp_date ,cr_date
-->
</div>
{% endblock %}

app/templates/app/orders.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h1 class="text-uppercase text-center"> Order Section </h1>
<div class="p-3">
   <div >
       <table style="width: 100%" class="table">
           <thead class="thead-default thead-dark">
               <!-- medicine, quantity, delivery_status,cr_date -->
               <tr>
                   <th>Medicine Name</th>
                   <th>Quantity</th>
                   <th>Total Price</th>
                   <th>Delivery Status</th>
                   <th>Order Date</th>         
                   <th colspan="2">Action</th>         
                           
               </tr>
               </thead>
               <tbody>
                   {% for o in orders %}
                   <tr>
                       <td>{{ o.medicine }}</td>
                       <td>{{ o.quantity }}</td>
                       <td>{{ o.total_price }}</td>
                       <td>{{ o.delivery_status }}</td>
                       <td>{{ o.cr_date }}</td>
                       <td><a href="{% url 'med_detail' o.medicine.id %}">View</a></td>
                       <td><a href="{% url 'order_review' o.id %}">Rate</a></td>
                    </tr>
                   {% endfor %}
               </tbody>
       </table>
   </div>
<!-- name, description, medicine_img, price -->
</div>
{% endblock %}

app/templates/app/profile_form.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="h1 text-center">
    {{ user }}'s <span class="text-uppercase"> Profile Update Form</span>
</div>
<div class="row mt-5">
    <div class="col-sm-8 offset-2">
        <form method="post">
            {% csrf_token %}
            
            <div id="div_id_bio" class="control-group"> 
                <label for="id_bio" class="control-label requiredField">
                    Bio<span class="asteriskField">*</span> </label>
                <div class="controls"> 
                    <textarea name="bio" cols="30" rows="3" class="textarea form-control" required=""
                        id="id_bio"></textarea> </div>
            </div>
            <div id="div_id_disease" class="control-group"> <label for="id_disease" class="control-label requiredField">
                    Disease<span class="asteriskField">*</span> </label>
                <div class="controls"> <textarea name="disease" cols="30" rows="3" class="textarea form-control" required=""
                        id="id_disease"></textarea> </div>
            </div>
            <div id="div_id_age" class="control-group"> <label for="id_age" class="control-label requiredField">
                    Age<span class="asteriskField">*</span> </label>
                <div class="controls"> <input type="number" name="age" class="numberinput form-control" required="" id="id_age"> </div>
            </div>
            <div id="div_id_full_address" class="control-group"> <label for="id_full_address"
                    class="control-label requiredField">
                    Full address<span class="asteriskField">*</span> </label>
                <div class="controls"> <textarea name="full_address" cols="30" rows="3" class="textarea form-control" required=""
                        id="id_full_address"></textarea> </div>
            </div>
            <div id="div_id_contact_no" class="control-group"> <label for="id_contact_no" class="control-label requiredField">
                    Contact no<span class="asteriskField">*</span> </label>
                <div class="controls"> <input type="text" name="contact_no" maxlength="20" class="textinput textInput form-control"
                        required="" id="id_contact_no"> </div>
            </div>
            <input type="submit" value="Submit" />
        </form>
        
    </div>

</div>

{% endblock %}

app/templates/app/store.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h1 class="text-uppercase text-center"> Medicine Store </h1>
<div class="row">
    {% for med in medicine_list %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="/media/{{ med.medicine_img }}" alt="Medicine image not found">
            <div class="card-body">
              <h5 class="card-title"> {{ med.name }} </h5>
              <!-- <p class="card-text">About Medicine :  {{ med.description }} </p> -->
              <p class="card-text">Price :  {{ med.price }} </p>
              <!-- <p class="card-text">Img :  {{ med.medicine_img }} </p> -->
              <a href="{% url 'med_detail' med.id %}" class="btn btn-outline-secondary">View Details</a>
              <!-- <form action="{% url 'med_cart' med.id %}" method="get">
                <input type="hidden" name="id" value="{{ med.id }}">
                <input type="submit" class="btn btn-secondary" value="Buy"></input>
              </form> -->
              <a href="/app/store/medicine/cart/{{ med.id }}" class="btn btn-secondary">Buy</a>
            </div>
          </div>
    </div>
    {% endfor %}
<!-- name, description, medicine_img, price -->
</div>
{% endblock %}